### ISSUE TITLE
秒杀异步校验问题

### ISSUE THREAD

**Issue by Masquerade6** [sunshinelyz/binghe#1]
例如，在秒杀活动中，我们出售1000件商品，此时在消息队列中存在1000个请求，如果后续仍然有用户发起秒杀请求，则后续的请求我们可以不再处理，直接向用户返回商品已售完的提示
------------------------------------------------------------------------------------------------------------------------------------------------------
这里不妥吧，校验的逻辑在MQ之后，如果校验过程中发现某些用户异常，那自然不能让他购买商品，那预定想要售出的商品就没法卖出那么多了，实际想要售出1000件，最后可能只卖了950件

**Comment by binghe001** [comment]
> ## 例如，在秒杀活动中，我们出售1000件商品，此时在消息队列中存在1000个请求，如果后续仍然有用户发起秒杀请求，则后续的请求我们可以不再处理，直接向用户返回商品已售完的提示
> 
> 这里不妥吧，校验的逻辑在MQ之后，如果校验过程中发现某些用户异常，那自然不能让他购买商品，那预定想要售出的商品就没法卖出那么多了，实际想要售出1000件，最后可能只卖了950件

有道理，可以再检验库存等校验逻辑中放过一些请求，让请求量大于库存量，在真正下单的时候保证库存不超卖，给你点赞！！！
